### ISSUE TITLE
Bartender for Classic Wow?

### ISSUE THREAD

**Issue by mqmq0** [Nevcairiel/Bartender4#1]
Hello Nevcairiel!

Maybe its not the best place to ask, but I could not find any better: Will there be a Classic Wow version of this wonderful addon?

**Comment by Nevcairiel** [comment]
Why don't you just try the current version.

**Comment by mqmq0** [comment]
Actually, I cannot, I do not have access for the beta. I'm just curious. 
But if you say, it will work there, then I'm okay with that.
Sorry to bother you here, I understand this is not the best place to ask these questions.
