### ISSUE TITLE
XP and reputation bars overlay Blizzard Art

### ISSUE THREAD

**Issue by tomvdbussche** [Nevcairiel/Bartender4#10]
Allowing to change the z-index for bars would help with overlay items. For example if XP / reputation bar is enabled, they overlay the Blizzard Art while in the default version they are drawn behind the art.

A simpler solution would just be to draw the Blizzard Art over the XP and reputation bars by default.

# Default
![blizzlike-bars](https://user-images.githubusercontent.com/5674397/64977939-a7a78f80-d8b4-11e9-92d6-77996a09c7b7.png)

# Bartender
![bartender-bars](https://user-images.githubusercontent.com/5674397/64977956-af673400-d8b4-11e9-82a0-f6383171255b.png)

**Comment by LudiusMaximus** [comment]
As a temporary workaround you could write a little Addon yourself that loads after Bartender and sets the https://wow.gamepedia.com/FrameStrata accordingly.
