### ISSUE TITLE
DF - Exit vehicle button missing

### ISSUE THREAD

**Issue by Wutname1** [Nevcairiel/Bartender4#100]
Steps to reproduce:
1. Disable Vehicle Bar
2. Get on Vehicle

Looks like `MainMenuBarVehicleLeaveButton` is attached to the `MainMenuBar` and since BT4 replaces that when you get on a vehicle the button is not displayed. Guessing need to detach it and add a mover the button also does not show up in Edit mode with BT4 enabled for the same reasons.

**Comment by Nevcairiel** [comment]
The Vehicle Bar's only purpose is to make the leave vehicle button movable. If you disable it, naturally it will not be present.

**Comment by Wutname1** [comment]
I will circle back with the person that was reporting it to me. Think there was a mixup between use blizzard vehicle ui and vehicle bar. I just did not catch it.
