### ISSUE TITLE
[Question] Is it possible to stop spells from auto adding to Bar 1?

### ISSUE THREAD

**Issue by Nillx** [Nevcairiel/Bartender4#101]
Currently i have Bar 1 hidden and filled with random spells because usually i dont have it fully populated and when i switch speccs it auto adds the new talents in to the empty slots. Is there a way to somehow turn that off?

**Comment by Nevcairiel** [comment]
This is Blizzard doing this, but you should be able to turn it off using this command:

/console AutoPushSpellToActionBar 0

**Comment by Nillx** [comment]
Oh amazing thanks!
