### ISSUE TITLE
Masque bar numbering is different (maybe old)

### ISSUE THREAD

**Issue by KonstantinosKoubetsos** [Nevcairiel/Bartender4#103]
In masque options where you can select individual bartender4 bars and change the skin, the numbering of the bars is different than bartender's. For example masque's bar number 3 is bartender's bar number 4, masque 5 -> bt 3 and masque 6 -> bt 2. I'm using the latest version in both addons.
Now maybe it's masque's problem or maybe it has something to do with blizzard numbering and the recent bartender change as well. Sorry if I post this on wrong addon Issues, if it's masque I will go post on their page.

**Comment by Nevcairiel** [comment]
Thanks, this should be fixed soon.
