### ISSUE TITLE
PushedTexture of AoE spell buttons does not go away

### ISSUE THREAD

**Issue by LudiusMaximus** [Nevcairiel/Bartender4#112]
With my hunter, I click the button for "Wild Spirits", "Binding Shot", "Sentinel Owl", or "Flare".
After clicking the button, the bright yellow PushedTexture frame appears around the button.
But it stays even after the spell is cast or cancelled (pressing ESC instead of clicking the ground area for the spell).

I also tried it with my shaman and "Earthquake" and it is the same.

Thanks for looking into this.

**Comment by Nevcairiel** [comment]
This is a known issue with how Blizzard handles the buttons when you use "on down" casting. Unfortunately no easy fix or workaround seems to present right now, but looking into other solutions.

**Comment by LudiusMaximus** [comment]
Ah, OK. Is there a way to disable "on down" casting, then? I would be fine with "on up" casting.

**Comment by Nevcairiel** [comment]
There is an option in the Bartender settings for it. But I may have found a work-around just now until Blizzard improves button functions again.

**Comment by Nevcairiel** [comment]
The workaround is available in the latest alpha version.
