### ISSUE TITLE
Question about the new macro/hotkey text options

### ISSUE THREAD

**Issue by Nillx** [Nevcairiel/Bartender4#113]
Noticed that you added an option to change the font and scale on macro/hotkey/count, do you think its possible to also let us move the text up/down and left/right? Im currently using a Masque skin and with the new update the macro/hotkey text is up in the button border, it would be nice if i can adjust the position.

![image](https://user-images.githubusercontent.com/34476875/200087653-85c089d1-9286-4273-827e-9a2f34f4dbd9.png)

**Comment by Nevcairiel** [comment]
The position is adjustable in the latest alpha

**Comment by Nillx** [comment]
Thank you, amazing change!
