### ISSUE TITLE
Toggle actions on key press instead of release

### ISSUE THREAD

**Issue by alex-iuga** [Nevcairiel/Bartender4#122]
The tooltip for this options says: "Note that the buttons need to be locked for actions to run on key press" but it also does when bars are not locked.
Furthermore, it would be nice if it only worked for keyPress and ignore mouse clicks. If I try to move a spell, it will also cast it.

**Comment by Nevcairiel** [comment]
Moving spells with the mouse either when the bars are unlocked, or by holding shift, will not cast them in recent versions of Bartender.

**Comment by alex-iuga** [comment]
Doesn't seem to be the case. Bartender is up to date, all other addons are disabled and behavior is same as described above.

**Comment by Nevcairiel** [comment]
I just tested it this second to make sure, it works as described.

**Comment by Nevcairiel** [comment]
Note that actual keyboard presses will alway follow the keypress setting, because there is no risk with moving spells there.

**Comment by Nevcairiel** [comment]
One thing that occured to me, this applies to retail only. The option to prevent casting when dragging is not available in Classic, as button execution is tightly controlled by what Blizzard allows.

**Comment by alex-iuga** [comment]
Thanks for taking the time and looking into this.
I uploaded 2 videos on youtube to show the behavior of bt4 vs aio
BT4: https://youtu.be/8Nn7tYlalB8
AIO: https://youtu.be/oqAMYKOGtpg

On AIO, it works as expected. onKeyPress only for key strokes and onKeyRelease for mouse.

**Comment by Nevcairiel** [comment]
You are obviously on Wrath, the behavior documented above only applies to retail - it is not currently supported the same way on wrath due to limitations imposed by Blizzard. Of course Blizzard cheats on their own action bars.
