### ISSUE TITLE
Disabling loss-of-control CD

### ISSUE THREAD

**Issue by alexzaworski** [Nevcairiel/Bartender4#13]
Hi—

Is there any way to disable the loss-of-control CD from displaying on buttons in bt4? It's pretty jarring in Classic. I tried [this addon](https://us.battle.net/forums/en/wow/topic/7200082635?page=1) which allegedly worked with bt4 at one point but didn't have any success.

**Comment by Nevcairiel** [comment]
Loss of Control CD should be disabled in the next update, to match default classic behavior.

**Comment by alexzaworski** [comment]
Howdy

This seems to have regressed in BCC, is that a deliberate change or will it be removed there as well?
