### ISSUE TITLE
bartender messes with edit mode

### ISSUE THREAD

**Issue by Pahn1988** [Nevcairiel/Bartender4#130]
11708x Interface/FrameXML/EditModeSystemTemplates.lua:631: attempt to perform arithmetic on local 'offsetY' (a nil value)
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:631: in function `GetBottomAnchoredHeight'
[string "@Interface/FrameXML/EditModeUtil.lua"]:39: in function `GetBottomActionBarHeight'
[string "@Interface/FrameXML/UIParent.lua"]:3083: in function `UIParentManageFramePositions'
[string "@Interface/FrameXML/UIParent.lua"]:2570: in function <Interface/FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3113: in function `UIParent_ManageFramePositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:640: in function <Interface/FrameXML/EditModeManager.lua:607>
[string "=[C]"]: in function `UpdateBottomActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:554: in function `UpdateActionBarLayout'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:655: in function `UpdateGridLayout'
[string "@Interface/FrameXML/ActionButton.lua"]:368: in function `UpdateAction'
[string "@Interface/FrameXML/ActionButton.lua"]:795: in function `OnEvent'
[string "@Interface/FrameXML/ActionButton.lua"]:216: in function <Interface/FrameXML/ActionButton.lua:213>

Locals:
self = MainMenuBar {
 0 = <userdata>
 QuickKeybindRightShadow = Texture {
 }
 UpdateSystemSettingAlwaysShowButtons = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:772
 UpdateMagnetismRegistration = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:506
 GetSnapOffsets = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:411
 UpdateFrameStrata = <function> defined @Interface/FrameXML/ActionBar.lua:194
 UpdateButtonArt = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:669
 IsFrameAnchoredToMe = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:469
 buttonTemplate = "MainBarActionBarButtonTemplate"
 ShowBase = <function> defined =[C]:-1
 IsShown = <function> defined @Interface/FrameXML/ActionBar.lua:286
 GetSelectionOffset = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:363
 ResetToDefaultPosition = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:148
 RefreshButtonArt = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:662
 GetScaledSelectionSides = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:355
 SelectSystem = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:534
 buttonArtDirty = false
 GetFrameMagneticEligibility = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:489
 AddLayoutChildren = <function> defined @Interface/SharedXML/LayoutFrame.lua:48
 IsBelowFrame = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:322
 UpdateSystemSettingIconSize = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:714
 SetScaleBase = <function> defined =[C]:-1
 HasActiveChanges = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:244
 GetScaledCenter = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:348
 DoesSettingDisplayValueEqual = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:268
 OnLoad = <function> defined @Interface/FrameXML/MainMenuBar.lua:6
 UpdateDisplayInfoOptions = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:279
 ActionBarPageNumber = Frame {
 }
 settingDisplayInfoMap = <table> {
 }
 addSystemIndexToName = true
 IsLayoutFrame = <function> defined @Interface/SharedXML/LayoutFrame.lua:36
 DoesSettingValueEqual = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:263
 MarkDirty = <function> defined @Interface/SharedXML/LayoutFrame.lua:90
 ShouldResetSettingsDialogAnchors = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:91
 dirtySettings = <table> {
 }
 UpdateGridLayout = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:648
 IsToTheLeftOfFrame = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:304
 GetSettingsDialogAnchor = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:288
 hasActiveChanges = false
 OnSystemLoad = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:3
 ClearFrameSnap = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:448
 GetCombinedCenterOffset = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:398
 SetupSettingsDialogAnchor = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:232
 IsShownOverride = <function> defined @Interface/FrameXML/ActionBar.lua:286
 dirty = false
 SetPointBase = <function> defined =[C]:-1
 UpdateSystem = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:586
 UpdateShownButtons = <function> defined @Interface/FrameXML/ActionBar.lua:198
 UpdateDirtySettings = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:112
 BreakSnappedFrames = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:431
 HideOverride = <function> defined @Interface/FrameXML/ActionBar.lua:313
 VehicleLeaveButton = MainMenuBarVehicleLeaveButton {
 }
 systemIndex = 1
 snappedFrames = <table> {
 }
 SetShownOverride = <function> defined @Interface/FrameXML/ActionBar.lua:298
 SetPointOverride = <function> defined @
 
 
 hello there, this is the whole error message from bugsack.
 ive got that error during lfr, there was no extra button for the seeds in castle nathria at xymox.
 this are the bars i have enabled:
 
![grafik](https://user-images.githubusercontent.com/74673519/202918275-4e9cd665-e157-4177-9465-e9bf528af470.png)

this is the version i use:
![grafik](https://user-images.githubusercontent.com/74673519/202918304-b8e8c070-d4a0-4f98-af34-7611176dc1cd.png)

im using the modern blizzard interface preset

**Comment by jcadduono** [comment]
I am getting this exact error millions of times when I go into combat in a keystone, though I have no way to attribute it to Bartender4 and was hoping Blizzard would simply add more error handling to the edit mode code. It is single handedly forcing me to turn off UI errors so I can't investigate possible issues with other addons in keys as well. I really hope edit mode gets more stable in the coming weeks.

**Comment by zaphon** [comment]
This has been plaguing me all day running leveling dungeons on a low level alt.

**Comment by Nevcairiel** [comment]
This should've been fixed by Blizzard. EditMode is largely all their issues.

**Comment by jpieczyrak** [comment]
It should.. but it is not..
And other addons (like elvui) somehow handles this without errors.
It would be nice to NOT have to switch to another addon.
