### ISSUE TITLE
Binding of Shift+Home and Ctrl+Home show on bars as S... and C...

### ISSUE THREAD

**Issue by james5272** [Nevcairiel/Bartender4#136]
So you can't see the full binding.  Any way this can be fixed?
![wowshifthome](https://user-images.githubusercontent.com/117467705/204848973-50e170ea-694e-4cd9-b25c-a03c9421dd81.png)

**Comment by Nevcairiel** [comment]
You would likely have to make the keybinding font smaller, or the button bigger. There is only so much space, and Home is a long key name.
