### ISSUE TITLE
icon on bars are not taken in the same order

### ISSUE THREAD

**Issue by YetAnotherDevWannabe** [Nevcairiel/Bartender4#139]
Picture is worth a thousand words :
Default UI (2 vertical columns) :
![image](https://user-images.githubusercontent.com/6054349/207146488-9c91515a-2d63-4084-89e4-b361213e2c97.png)

Bartender 4 (6 horizontal rows) :
![image](https://user-images.githubusercontent.com/6054349/207146384-c92639b7-5770-43c6-8741-94cb6fcf889f.png)

Is there a way to have them behave the same way ?

**Comment by ilysqt** [comment]
You can just go to the settings of the bar and change the growth direction. For example in your 2nd pic it grows up from bottom right. In the first screenshot it grows down from the Top left. Just mess with the "Vertical Growth" and "Horizontal Growth"  options in the bar config menu.
