### ISSUE TITLE
Bar toggle code not working for bars 7 and 8

### ISSUE THREAD

**Issue by aggietallboy** [Nevcairiel/Bartender4#140]
Hi All, 
I am trying to set a toggle macro for bars 7 and 8 using the toggle code that floats around:

/run Bartender4.Bar.barregistry["7"]:SetVisibilityOption("always",not Bartender4.Bar.barregistry["7"]:GetVisibilityOption("always"))

This works great for bars up to 6, but then on 7 and 8 it seems to fail completely.

**Comment by Nevcairiel** [comment]
Internally, bars are named according to the action page they correspond to, not the visible name. Try 13 and 14.

Note that this kind of usage is not really supported.

**Comment by aggietallboy** [comment]
Thank you so much for the quick reply!!
Action bar 7:
/run Bartender4.Bar.barregistry["14"]:SetVisibilityOption("always",not Bartender4.Bar.barregistry["14"]:GetVisibilityOption("always"))

Action bar 8:
/run Bartender4.Bar.barregistry["15"]:SetVisibilityOption("always",not Bartender4.Bar.barregistry["15"]:GetVisibilityOption("always"))

This is my stopgap to make a fishing bar
