### ISSUE TITLE
Keyring button missing for classic.

### ISSUE THREAD

**Issue by gelsbern** [Nevcairiel/Bartender4#16]
They have enabled keyrings for classic, keyring button is missing.

**Comment by ramboozer** [comment]
+1

**Comment by ProbablyHackng** [comment]
I have a local branch to fix this I can create a PR for if you enable PR permissions

**Comment by SwimmingTiger** [comment]
@ProbablyHackng Where is your local branch? I am a addon collection author and I need the patch.

**Comment by SwimmingTiger** [comment]
I wrote a patch myself:
https://github.com/SwimmingTiger/WowBigfootClassic/commit/7eb7a5983577ddf5fb3640bddbf761df04fbd7f9

**Comment by ramboozer** [comment]
That patch does nothing more then have the Keyring show. but clicking it still doesn't open the correct bag...at least for me

**Comment by ProbablyHackng** [comment]
I was hoping that @Nevcairiel could enable PR so I could submit it from my machine, but I can fork if necessary. I added back the state this project used to be where it can be toggled from the option menu.

**Comment by Nevcairiel** [comment]
You can't actually disable Pull Requests, so not sure where you got that idea that it needs enabling. Even  when not logged in I see the Pull Request option at the top.

In any case, I'll likely work on this on the weekend.

**Comment by ProbablyHackng** [comment]
Sorry, I just didn't understand how contribution works on GitHub....I'll submit one

**Comment by ProbablyHackng** [comment]
#17 submitted
