### ISSUE TITLE
(SUGGESTION) Increase the number of maximum buttons on the bar from 12 to 16

### ISSUE THREAD

**Issue by Blueraven29** [Nevcairiel/Bartender4#164]
As the name suggest, it would be great to increase the lenght of the bar by adding additional buttons and instead of having a limit of 12, have i of 16 or 20, if possible.

**Comment by Nevcairiel** [comment]
Bartender4 follows the design of Blizzards action-bar subdivision of 12 per bar. There are no extra "buttons" to add, as they are in use by the other bars.
