### ISSUE TITLE
/click BT4Button1 is not work

### ISSUE THREAD

**Issue by jefflwq** [Nevcairiel/Bartender4#165]
since 10.0.5,  when check "Toggle actions on key press instead of release" ， macro "/click BT4Button1" is not work,
when uncheck "Toggle actions on key press instead of release" ， macro "/click BT4Button1" will work,

**Comment by Nevcairiel** [comment]
This is a game bug. I think you can fix it by specifying which button should click, eg. /click BT4Button1 LeftButton
