### ISSUE TITLE
Lua error on changing talent loadouts when a spell in a flyout changes

### ISSUE THREAD

**Issue by WanderingFox** [Nevcairiel/Bartender4#167]
This happens specifically on my rogue when I change builds that swap between numbing and atrophic poison

```
353x ...er4/libs/LibActionButton-1.0-106/LibActionButton-1.0.lua:2302: IsSpellInRange(): Invalid spell slot
[string "=[C]"]: in function `IsSpellInRange'
[string "@Bartender4/libs/LibActionButton-1.0-106/LibActionButton-1.0.lua"]:2302: in function `IsUnitInRange'
[string "@Bartender4/libs/LibActionButton-1.0-106/LibActionButton-1.0.lua"]:2218: in function `IsInRange'
[string "@Bartender4/libs/LibActionButton-1.0-106/LibActionButton-1.0.lua"]:1449: in function <...er4/libs/LibActionButton-1.0/LibActionButton-1.0.lua:1432>

Locals:
(*temporary) = nil
(*temporary) = "spell"
(*temporary) = nil
```

The error count continues up infinitely until a reload at which point it stops and behaves as expected until I change talents again.

**Comment by ninthwalker** [comment]
I also receieve this same exact error when swapping between specs. Demo -> Destro specifically. Not suire what talent in destro is doing it though, and /reloading fixes it, but is very much annoying.

**Comment by ninthwalker** [comment]
Awesome, thanks for jumping on it quick!
