### ISSUE TITLE
Patch 10.1.5 - Micro Menu issues

### ISSUE THREAD

**Issue by Nillx** [Nevcairiel/Bartender4#172]
Seems blizzard made the micro menu bigger and the "hitbox" changed. When using the option Fade Out  it no longer shows up when my cursor is near the edge (i can still press on the buttons but they are invisible). Example:

https://imgur.com/a/1bvIRSW

**Comment by FloatingUpstream** [comment]
I have opened a PR for this, basically just adjusting the button sizes to the current values of the blizzard UI.
