### ISSUE TITLE
Micro Menu broken on Wotlk PTR

### ISSUE THREAD

**Issue by Fishdumpster** [Nevcairiel/Bartender4#175]
My micro menu on the PTR is locked at the bottom of the screen and totally unresponsive to all positioning settings. It doesn't become highlighted and moveable at all when unlocking the bars. Attached screenshot displays where the micromenu is now permanently locked.

![WoWScrnShot_091423_201403](https://github.com/Nevcairiel/Bartender4/assets/143992826/4d4172af-bee6-4a23-b8a4-c8df2622b27f)

**Comment by sofar** [comment]
You can bypass this bug by editing line `65` of `MicroMenu.lua` and commenting the entire line (just prepend `--`).
