### ISSUE TITLE
Button glow for procs on macros - patch 10.2 

### ISSUE THREAD

**Issue by Armleg** [Nevcairiel/Bartender4#179]
Since the patch 10.2 hit today
Any kind of procc that would normally be indicated with a glow around the actionbar button, does not work if that button is a macro.
even a simple macro like:
#showtooltip 
/cast X

This have always worked as you would expect up untill the 10.2 patch hit today.
my specific case is a Enveloping mist macro, where as after 3 kicks when Chi-ji is up, my Enveloping mist becomes instant cast and usually glows, indicating its instant cast.
The macro i use and have used:
#showtooltip
/cast [target=mouseover,exists] Enveloping Mist; Enveloping Mist

- so just a simple macro, nothing weird about the macro itself, this problem stems from Bartender4.

/Armleg

**Comment by lennestal** [comment]
Same issue here. None of my macros glow since 10.2. The button glow on macros still works normally on the default UI, so it does indeed seem to be a problem with Bartender.

**Comment by Nevcairiel** [comment]
This should be fixed in the upcoming update
