### ISSUE TITLE
Feature request - stop creating new profiles upon logging in on a new character

### ISSUE THREAD

**Issue by Knbi** [Nevcairiel/Bartender4#183]
It feels somewhat pointless creating a new profile every single time you log in on a new character, it just clutters the list of profiles for no reason whatsoever. If a user wants to use a new profile he will create it, "Default" profile should be what Bartender defaults to upon logging on a character that has no specified profile for bartender to use.

**Comment by Nevcairiel** [comment]
This is an intentional design decision.
