### ISSUE TITLE
Season of Discovery. Interface Action Failed Because of an Addon

### ISSUE THREAD

**Issue by alhoant** [Nevcairiel/Bartender4#187]
Bartender lates version.

I get this message quite often when in combat. Here is the taint.log file entries:

1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - 
1/5 21:39:41.662      Interface/AddOns/Bartender4/libs/LibWindow-1.1/LibWindow-1.1.lua:178 RestorePosition()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:313 BT4BarBlizzardArt:LoadPosition()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:238 ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.662      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.662      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - SecureStateDriverManager:SetAttribute()
1/5 21:39:41.662      Interface/FrameXML/SecureStateDriver.lua:18
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:459 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.662      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.662      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - SecureStateDriverManager:SetAttribute()
1/5 21:39:41.662      Interface/FrameXML/SecureStateDriver.lua:19
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:459 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.662      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.662      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - BT4BarBlizzardArt:SetAttribute()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:463 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.662      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.662      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - SecureStateDriverManager:SetAttribute()
1/5 21:39:41.662      Interface/FrameXML/SecureStateDriver.lua:10
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:524 BT4BarBlizzardArt:ApplyVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:513 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.662      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.662      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - SecureStateDriverManager:SetAttribute()
1/5 21:39:41.662      Interface/FrameXML/SecureStateDriver.lua:11
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:524 BT4BarBlizzardArt:ApplyVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:513 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.662      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.662      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - 
1/5 21:39:41.662      Interface/AddOns/Bartender4/libs/LibWindow-1.1/LibWindow-1.1.lua:178 RestorePosition()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:313 BT4BarBlizzardArt:LoadPosition()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:238 ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.662      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.662      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - SecureStateDriverManager:SetAttribute()
1/5 21:39:41.662      Interface/FrameXML/SecureStateDriver.lua:18
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:459 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.662      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.662      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - SecureStateDriverManager:SetAttribute()
1/5 21:39:41.662      Interface/FrameXML/SecureStateDriver.lua:19
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:459 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.662      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.662      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - BT4BarBlizzardArt:SetAttribute()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:463 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.662      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.662      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - SecureStateDriverManager:SetAttribute()
1/5 21:39:41.662      Interface/FrameXML/SecureStateDriver.lua:10
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:524 BT4BarBlizzardArt:ApplyVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:513 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.662      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.662      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - SecureStateDriverManager:SetAttribute()
1/5 21:39:41.662      Interface/FrameXML/SecureStateDriver.lua:11
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:524 BT4BarBlizzardArt:ApplyVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:513 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.662      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.662      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - 
1/5 21:39:41.662      Interface/AddOns/Bartender4/libs/LibWindow-1.1/LibWindow-1.1.lua:178 RestorePosition()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:313 BT4BarBlizzardArt:LoadPosition()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:238 ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.662      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.662      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - SecureStateDriverManager:SetAttribute()
1/5 21:39:41.662      Interface/FrameXML/SecureStateDriver.lua:18
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:459 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.662      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.662      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - SecureStateDriverManager:SetAttribute()
1/5 21:39:41.662      Interface/FrameXML/SecureStateDriver.lua:19
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:459 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.662      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.662      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - BT4BarBlizzardArt:SetAttribute()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:463 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.662      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.662      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - SecureStateDriverManager:SetAttribute()
1/5 21:39:41.662      Interface/FrameXML/SecureStateDriver.lua:10
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:524 BT4BarBlizzardArt:ApplyVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:513 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.662      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.662      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.662      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.662  An action was blocked in combat because of taint from Bartender4 - SecureStateDriverManager:SetAttribute()
1/5 21:39:41.662      Interface/FrameXML/SecureStateDriver.lua:11
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:524 BT4BarBlizzardArt:ApplyVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:513 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.662      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.664      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.664      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.664      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.664      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.664  An action was blocked in combat because of taint from Bartender4 - 
1/5 21:39:41.664      Interface/AddOns/Bartender4/libs/LibWindow-1.1/LibWindow-1.1.lua:178 RestorePosition()
1/5 21:39:41.664      Interface/AddOns/Bartender4/Bar.lua:313 BT4BarBlizzardArt:LoadPosition()
1/5 21:39:41.664      Interface/AddOns/Bartender4/Bar.lua:238 ApplyConfig()
1/5 21:39:41.664      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.664      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.664      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.664      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.664  An action was blocked in combat because of taint from Bartender4 - SecureStateDriverManager:SetAttribute()
1/5 21:39:41.664      Interface/FrameXML/SecureStateDriver.lua:18
1/5 21:39:41.664      Interface/AddOns/Bartender4/Bar.lua:459 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.664      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.664      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.664      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.664      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.664      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.664  An action was blocked in combat because of taint from Bartender4 - SecureStateDriverManager:SetAttribute()
1/5 21:39:41.664      Interface/FrameXML/SecureStateDriver.lua:19
1/5 21:39:41.664      Interface/AddOns/Bartender4/Bar.lua:459 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.664      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.664      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.664      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.664      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.664      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.664  An action was blocked in combat because of taint from Bartender4 - BT4BarBlizzardArt:SetAttribute()
1/5 21:39:41.664      Interface/AddOns/Bartender4/Bar.lua:463 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.664      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.664      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.664      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.664      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.664      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.664  An action was blocked in combat because of taint from Bartender4 - SecureStateDriverManager:SetAttribute()
1/5 21:39:41.664      Interface/FrameXML/SecureStateDriver.lua:10
1/5 21:39:41.664      Interface/AddOns/Bartender4/Bar.lua:524 BT4BarBlizzardArt:ApplyVisibilityDriver()
1/5 21:39:41.664      Interface/AddOns/Bartender4/Bar.lua:513 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.664      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.664      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.664      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.664      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.664      Interface/FrameXML/MainMenuBar.lua:108
1/5 21:39:41.664  An action was blocked in combat because of taint from Bartender4 - SecureStateDriverManager:SetAttribute()
1/5 21:39:41.664      Interface/FrameXML/SecureStateDriver.lua:11
1/5 21:39:41.664      Interface/AddOns/Bartender4/Bar.lua:524 BT4BarBlizzardArt:ApplyVisibilityDriver()
1/5 21:39:41.664      Interface/AddOns/Bartender4/Bar.lua:513 BT4BarBlizzardArt:InitVisibilityDriver()
1/5 21:39:41.664      Interface/AddOns/Bartender4/Bar.lua:242 ApplyConfig()
1/5 21:39:41.664      Interface/AddOns/Bartender4/BlizzardArt.lua:156 BT4BarBlizzardArt:ApplyConfig()
1/5 21:39:41.664      Interface/AddOns/Bartender4/BlizzardArt.lua:129
1/5 21:39:41.664      MainMenuBar_UpdateKeyRing()
1/5 21:39:41.664      Interface/FrameXML/MainMenuBar.lua:108

**Comment by Nevcairiel** [comment]
This should be fixed in the update coming out momentarily.
