### ISSUE TITLE
Spells requiring a reagent are showing a cast counter of zero

### ISSUE THREAD

**Issue by Dyaxler** [Nevcairiel/Bartender4#19]
I think Blizzard broke...

`currentCharges, maxCharges, cooldownStart, cooldownDuration, chargeModRate = GetSpellCharges(spellId or "spellName")`

...this function is no longer returning anything. Not only Soul Shards but any spell that requires a Reagent such as Paladins Greater Blessings, Druids Rebirth, Mage Portals etc.

**Comment by tehOPEologist** [comment]
also seeing this for rogue reagents like flash/blind powder

**Comment by Nevcairiel** [comment]
This was indeed broken by Blizzard, nothing I can do about that until they fix it (at which point it hopefully just works again).

**Comment by tehOPEologist** [comment]
this looks re-broken again?  logged in today and don't see any reagent quantities over some spells (eg: vanish, etc)...  can you confirm it's blizz messing with their API again?  thanks!

**Comment by tylermwatts** [comment]
> this looks re-broken again? logged in today and don't see any reagent quantities over some spells (eg: vanish, etc)... can you confirm it's blizz messing with their API again? thanks!

Blizz's change may have been reverted, because I rolled back to Bartender4 version `4.8.9-2-gc5bd6e2-classic` that was released on 12/15/19, and the quantities have reappeared.

**Comment by Dyaxler** [comment]
v4.9.0 from this past Jan works fine for me! Not sure what's going on with you guys. Try running just Bartender alone and see if your issues are gone. If so then you'll have to enable your addons one at a time to figure out which one is conflicting. Yeah, I know PITA!

**Comment by tylermwatts** [comment]
> Try running just Bartender alone and see if your issues are gone
Nope. Tried loading the newest version of Bartender as the only addon, disabling all other addons, and the latest version still doesn't show reagent counts on spells. Reverting to the 12/15/19 release still fixes the issue in this case.
