### ISSUE TITLE
TWW Beta - LUA Errors

### ISSUE THREAD

**Issue by Andf** [Nevcairiel/Bartender4#199]
Hello!
Not sure if BT is expected to work in TWW, it's tagged with 11.0 game version.

Anyway, receiving the following LUA errors:
1. `24x ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: [string " local state, type, action = ......"]:12: attempt to call global 'IsHelpfulSpell' (a nil value)24x ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: [string " local state, type, action = ......"]:12: attempt to call global 'IsHelpfulSpell' (a nil value)[string "=[C]"]: ?[string "@Blizzard_FrameXML/RestrictedExecution.lua"]:430: in function <...aceBlizzard_FrameXML/RestrictedExecution.lua:419>[string "=(tail call)"]: ?[string "=(tail call)"]: ?[string "@Blizzard_FrameXML/SecureHandlers.lua"]:115: in function <Blizzard_FrameXML/SecureHandlers.lua:110>[string "=[C]"]: ?[string "=[C]"]: in function `SetAttribute'[string "@Bartender4/StateBar.lua"]:241: in function `UpdateStates'[string "@Bartender4/StateBar.lua"]:378: in function `UpdateSelfCast'[string "@Bartender4/ActionBar.lua"]:142: in function `UpdateSelfCast'[string "@Bartender4/ActionBar.lua"]:133: in function `UpdateButtonConfig'[string "@Bartender4/ActionBar.lua"]:364: in function `SetGrid'...[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:95: in function `SetUpMajorFactionList'[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:88: in function `RefreshMajorFactionList'[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:83: in function `RefreshOverlay'[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:75: in function <...pansionLandingPage/Blizzard_WarWithinLandingPage.lua:71>[string "=[C]"]: in function `CreateFrame'[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:47: in function `CreateOverlay'[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>
Locals:(*temporary) = "Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: [string " local state, type, action = ......"]:12: attempt to call global 'IsHelpfulSpell' (a nil value)"`

2. `77x ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: [string " local state, type, action = ......"]:12: attempt to call global 'IsHelpfulSpell' (a nil value)77x ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: [string " local state, type, action = ......"]:12: attempt to call global 'IsHelpfulSpell' (a nil value)[string "=[C]"]: ?[string "@Blizzard_FrameXML/RestrictedExecution.lua"]:430: in function <...aceBlizzard_FrameXML/RestrictedExecution.lua:419>[string "=(tail call)"]: ?[string "=(tail call)"]: ?[string "@Blizzard_FrameXML/SecureHandlers.lua"]:499: in function <Blizzard_FrameXML/SecureHandlers.lua:473>[string "=[C]"]: in function `SetAttribute'[string "@Blizzard_FrameXML/SecureHandlers.lua"]:743: in function <Blizzard_FrameXML/SecureHandlers.lua:725>[string "=(tail call)"]: ?[string "@Bartender4/libs/LibActionButton-1.0-111/LibActionButton-1.0.lua"]:602: in function `func'[string "@Bartender4/ButtonBar.lua"]:272: in function `ForAll'[string "@Bartender4/StateBar.lua"]:306: in function `UpdateStates'[string "@Bartender4/StateBar.lua"]:378: in function `UpdateSelfCast'...[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:95: in function `SetUpMajorFactionList'[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:88: in function `RefreshMajorFactionList'[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:83: in function `RefreshOverlay'[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:75: in function <...pansionLandingPage/Blizzard_WarWithinLandingPage.lua:71>[string "=[C]"]: in function `CreateFrame'[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:47: in function `CreateOverlay'[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>
Locals:(*temporary) = "Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: [string " local state, type, action = ......"]:12: attempt to call global 'IsHelpfulSpell' (a nil value)"`

3. `310x ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: [string " local state, type, action = ......"]:12: attempt to call global 'IsHelpfulSpell' (a nil value)310x ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: [string " local state, type, action = ......"]:12: attempt to call global 'IsHelpfulSpell' (a nil value)[string "=[C]"]: ?[string "@Blizzard_FrameXML/RestrictedExecution.lua"]:430: in function <...aceBlizzard_FrameXML/RestrictedExecution.lua:419>[string "=(tail call)"]: ?[string "=(tail call)"]: ?[string "@Blizzard_FrameXML/SecureHandlers.lua"]:499: in function <Blizzard_FrameXML/SecureHandlers.lua:473>[string "=[C]"]: in function `SetAttribute'[string "@Blizzard_FrameXML/SecureHandlers.lua"]:743: in function <Blizzard_FrameXML/SecureHandlers.lua:725>[string "=(tail call)"]: ?[string "@Bartender4/libs/LibActionButton-1.0-111/LibActionButton-1.0.lua"]:1754: in function <...er4/libs/LibActionButton-1.0/LibActionButton-1.0.lua:1617>[string "@Bartender4/libs/LibActionButton-1.0-111/LibActionButton-1.0.lua"]:1286: in function <...er4/libs/LibActionButton-1.0/LibActionButton-1.0.lua:1268>
Locals:(*temporary) = "Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: ...aceBlizzard_FrameXML/RestrictedExecution.lua:430: Call failed: [string " local state, type, action = ......"]:12: attempt to call global 'IsHelpfulSpell' (a nil value)" `

**Comment by Nevcairiel** [comment]
The latest alpha version should fix this and support TWW, more testing needed.

**Comment by Andf** [comment]
I have just downloaded it, it seems to be working fine with latest TWW beta, many thanks!

I'll open a new issue if I notice something else :)
