### ISSUE TITLE
Error loading LibStub inside LibClassicSpellActionCount

### ISSUE THREAD

**Issue by Desik** [Nevcairiel/Bartender4#20]
`21x Error loading LibClassicSpellActionCount-1.0-3\LibStub\LibStub-1.0.2-70000.lua`

Getting this error on login, seems like the LibClassicSpellActionCount-1.0 folder is not pulling the LibStub folder when packaging

I wasn't sure where to post this issue but another solution is to simply remove Libstub from the library TOC

`## LibStub\LibStub.lua`

**Comment by Nevcairiel** [comment]
That would be an issue with that library, not Bartender. Bartender simply embeds the library, it does not require (or recommend) to install it seperately.

I recommend to report it at https://www.curseforge.com/wow/addons/libclassicspellactioncount/
