### ISSUE TITLE
Allow Color/Size Set and Change on Taskbar BindKeys

### ISSUE THREAD

**Issue by gcallen** [Nevcairiel/Bartender4#21]
It would be useful to be able to change the color and size of the bound key showing on the taskbar buttons.  Different characters have different spell colors and the dim white color and small size make it very hard to see them for many classes.  If a player is in battle and loses touch with the keyboard, it would make it easier and faster to re-acquire hand placement.  
Some players do not type and others, like me, may not use common finger placement because of a disability.

**Comment by Nevcairiel** [comment]
This is now implementated in the latest alpha version
