### ISSUE TITLE
Feature Request: More bars

### ISSUE THREAD

**Issue by Moezenka** [Nevcairiel/Bartender4#212]
Hi,

I am running out of space and was wondering if it's possible to add more bars?
*As a druid, a lot of the bars are tied to stances so I have less to work with.*

There's something another addon called `Button Forge` that does this.
Ideally it would be nice if i could use a single addon for this.

**Comment by Nevcairiel** [comment]
Bartender just offers you access to all Blizzard bars. More are not possible.
