### ISSUE TITLE
WoW Wrath of the Lich King Classic 

### ISSUE THREAD

**Issue by pennkao** [Nevcairiel/Bartender4#214]
----------------------------------------
    Lua Stack
----------------------------------------
[string "		local state = ......"]:11: in function <[string "		local state = ......"]:1>
(tail call): ?
[C]: ?
Interface/FrameXML/RestrictedExecution.lua:484: in function <Interface/FrameXML/RestrictedExecution.lua:447>
Interface/FrameXML/RestrictedFrames.lua:713: in function 'RunFor'
[string "			local frame = self:GetFrameRef("updateBu..."]:2: in function <[string "			local frame = self:GetFrameRef("updateBu..."]:1>
(tail call): ?
[C]: ?
Interface/FrameXML/RestrictedExecution.lua:484: in function <Interface/FrameXML/RestrictedExecution.lua:447>
(tail call): ?
Interface/FrameXML/SecureHandlers.lua:499: in function <Interface/FrameXML/SecureHandlers.lua:473>
[C]: in function 'SetAttribute'
Interface/FrameXML/SecureHandlers.lua:743: in function <Interface/FrameXML/SecureHandlers.lua:725>
(tail call): ?
...er4/libs/LibActionButton-1.0/LibActionButton-1.0.lua:602: in function 'func'
Interface/AddOns/Bartender4/ButtonBar.lua:272: in function 'ForAll'
Interface/AddOns/Bartender4/StateBar.lua:306: in function 'UpdateStates'
Interface/AddOns/Bartender4/StateBar.lua:378: in function 'UpdateSelfCast'
Interface/AddOns/Bartender4/ActionBar.lua:137: in function 'UpdateSelfCast'
Interface/AddOns/Bartender4/ActionBar.lua:314: in function 'UpdateButtons'
Interface/AddOns/Bartender4/ActionBar.lua:52: in function 'ApplyConfig'
Interface/AddOns/Bartender4/ActionBars.lua:340: in function 'Create'
Interface/AddOns/Bartender4/ActionBars.lua:146: in function <Interface/AddOns/Bartender4/ActionBars.lua:138>
[C]: ?
...AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:66: in function <...AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
...AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:523: in function 'EnableAddon'
...AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:536: in function 'EnableAddon'
...AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:626: in function <...AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by Nevcairiel** [comment]
Wrath is not supported, only official Classic Era and Cataclysm are supported.
