### ISSUE TITLE
Possesbar paging - classic

### ISSUE THREAD

**Issue by dennyh** [Nevcairiel/Bartender4#23]
When using the posses bar paging option on either bar 1 or bar 2 noting happens when Mind Controling an NPC with a priest.
This is the custom conditional box: [overridebar][possessbar][shapeshift]posses;1

Normaly the controls for the mind controled target shows up on the pet bar.

**Comment by Nevcairiel** [comment]
Mind Control is only ever supposed to show up on the Pet Bar, I believe. I don't think Classic uses the Possess Bar at all, I don't believe that was a feature back in Vanilla.
