### ISSUE TITLE
Classic: Prowl Paging not working Correctly

### ISSUE THREAD

**Issue by Mushoz** [Nevcairiel/Bartender4#24]
I am setting up bar 1, which pages to 7 in cat form, and 8 in cat form while prowled. The bar itself reflects this correctly when going into cat form, and the keybindings also correctly switch. The button "A" which is auto-attack in caster form correctly changes to prowl in cat form.

However, upon hitting the prowl button a bug seems to occur. The bar correctly changes to page 8 as setup. With my mouse I can click these abilities just fine. However, keybindings do not change with the changed page. The button "A" does not become pounce as it should be, but remains prowl, which means I am simply going to exit stealth form if I press it.

Any ideas what's causing this issue?

**Comment by Nevcairiel** [comment]
Make sure your keybindings are actually bound to the Bartender bar, and not the blizzard bar, otherwise it may appear to function but then stops in these cases.

**Comment by Mushoz** [comment]
That was it, my apologies for not reading the documentation before jumping to conclusions.
