### ISSUE TITLE
[Feature Request] Hidden bars unless spellbook open

### ISSUE THREAD

**Issue by Mushoz** [Nevcairiel/Bartender4#25]
I use bartender purely for keybinding my abilities. I do not require them to be visible at all. Currently, when making new binds I have to unhide the bar, set up the abilities and binds, and hide them again. It would be amazing if bars would be and stay hidden unless I open up the spellbook. Would this be a possible addition for this amazing addon?

I do now it has been implemented in a very old version of Bartender by someone manually, as can be read about here: https://www.reddit.com/r/WowUI/comments/64n6zi/helphep_bartender_4_show_conditions_when/

But I'd rather use an up-to-date version that is compatible with classic :) Perhaps it is useful to see how that person implemented said functionality.

**Comment by Nevcairiel** [comment]
The visibility conditions in Bartender are driven by Blizzards Macro Conditions, and since there is no macro condition for viewing the spellbook, I'm afraid thats not going to make it in.

**Comment by Mushoz** [comment]
I know how it's currently working, but the edited version shows that it's technically possible and probably a welcome addition for some people.

In case that deviates too much from the current design, would it perhaps be possible to quickly toggle the visibility via a /command or keybind so it would be possible to quickly show/hide the bars instead of having to open up the config screen?

**Comment by Nevcairiel** [comment]
You can hack together anything and call it working with a bit disclaimer under what conditions it may work, but visibility conditions in Bartender are guaranteed to always work under any circumstances.

slash commands exist to toggle that if you want to:
/bt4 bars 1 visibility always
(not tested right now, but i think that should be right)
