### ISSUE TITLE
Deleted profiles still showing up in 'Existing Profiles' dropdown

### ISSUE THREAD

**Issue by jcslater09** [Nevcairiel/Bartender4#26]
I'm trying to delete old profiles, but for some reason they still show up in the 'Existing Profiles' dropdown.  They get removed from the 'Copy From' and 'Delete a Profile' dropdowns, but nothing I do seems to remove them from the Existing Profiles.  I've tried reloading, restarting the client, deleting my cache folder, even went to the configuration file for bartender and confirmed that they were deleted from that, so I'm not sure where it's pulling these strings from.

**Comment by Nevcairiel** [comment]
"Existing Profiles" not only shows actually existing profiles, but it also shows typical default options for your Character, your Realm and your Class. So if we're talking about those, then those showing up in the profile selector is expected.
