### ISSUE TITLE
[9.0 - SL] CalculateAction

### ISSUE THREAD

**Issue by XinYenFon** [Nevcairiel/Bartender4#28]
If an action fails to execute for any reason, eg; if I press Stormstrike (keybinded to 1) or Fleshcraft (Shift+A) following error occurs... This error does not happen if I use Ghost Wolf (E), Astral Shift (Shift+E) etc...

edit: Fleshcraft has no reason for fail its channel spell and unlike Stormstrike it does not require any target...

```
Message: Interface\FrameXML\SecureTemplates.lua:332: attempt to call method 'CalculateAction' (a nil value)
Time: Sat Jul 18 14:48:38 2020
Count: 9
Stack: Interface\FrameXML\SecureTemplates.lua:332: attempt to call method 'CalculateAction' (a nil value)
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\FrameXML\SecureHandlers.lua"]:40: in function <Interface\FrameXML\SecureHandlers.lua:39>
[string "@Interface\FrameXML\SecureHandlers.lua"]:268: in function <Interface\FrameXML\SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface\FrameXML\SecureHandlers.lua"]:296: in function <Interface\FrameXML\SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>
```

**Comment by Nevcairiel** [comment]
Blizzard screwed up the action bar stuff a bit on the beta. Hopefully they'll change it to resolve these problems.

**Comment by XinYenFon** [comment]
I assume I should expect fix from their side and safe to close this issue?

**Comment by Nevcairiel** [comment]
Expect? Not sure they really know about the consequences of their change yet, so we'll see.

**Comment by Nevcairiel** [comment]
This issue was resolved in todays beta update, and Bartender4 should function more or less now. More testing and fixing on the beta will happen in the coming days now that its actually usable.
