### ISSUE TITLE
Petbar not hidden after entering vehicle

### ISSUE THREAD

**Issue by LudiusMaximus** [Nevcairiel/Bartender4#3]
I see you are currently working on Bartender4. Thanks for your ongoing efforts!

I know that there are probably more pressing issues for you at the moment, but regarding [this](https://www.wowace.com/projects/bartender4/issues/1487), could you maybe just give me a hint where to fix this in your code?

I would be happy to make fork and pull request, if i get this fixed.

Thanks again!

**Comment by Nevcairiel** [comment]
The only reason they would show is if something is showing them manually, or Blizzard is not properly firing events to update the visibility handler.

My guess is on whatever is hiding your UI when you talk to the NPC causing this. It seems likely that it might disrupt the show/hide process.

**Comment by LudiusMaximus** [comment]
Ah, you are right! Thanks. I can now look into this myself.

**Comment by LudiusMaximus** [comment]
Is there a way for another addon to determine if a Bartender4 frame should be hidden according to the current situation and user config?

**Comment by Nevcairiel** [comment]
The visibility control sets an attribute on the bar, "state-vis", which one could read, its either "show", "hide", or "fade" (or "fade:xx" with xx being a percentage)

**Comment by LudiusMaximus** [comment]
Great, thanks a lot. This prevents my mod from bringing back unwanted frames after the UI fade in:
`if BT4BarPetBar and BT4BarPetBar:GetAttribute("state-vis") == "show" then BT4BarPetBar:Show() end`

**Comment by LudiusMaximus** [comment]
I just realised that the micro menu gets hidden, when I am on a vehicle. This is really the case even if Bartender is the only addon I activate.
