### ISSUE TITLE
Classic: reagent count for spells is not displayed

### ISSUE THREAD

**Issue by carlpoole** [Nevcairiel/Bartender4#32]
The reagent count on spells has been missing from my bars for some time. It reappears if I roll back to the 12/15/19 version of Bartender 4 for Classic.

**Comment by Nevcairiel** [comment]
I logged in to Classic just yesterday and counts on my soul shards are showing perfectly.

**Comment by Nevcairiel** [comment]
Can only recommend to confirm you are actually using the classic version of the addon, because the retail version will actually work, but lack classic-specific functionality like adding the reagent count, which Blizzard disabled for classic.

**Comment by carlpoole** [comment]
Thanks for the super fast reply. I went back and checked addons to see what it might be. It wasn't working originally so I rolled it back but then I just upgraded back to current and it is working now. I'm assuming it might have got swapped out for the retail version at some point.
