### ISSUE TITLE
Working in 9.0.2

### ISSUE THREAD

**Issue by suark** [Nevcairiel/Bartender4#36]
I had to copy what you did, adding `BackdropTemplateMixin and "BackdropTemplate" or nil)` to all places using `CreateFrame`, in the supporting libs. Then it was all working without issue.

I know you can't update those libs as part of your project but I just wanted to let you know that that's all it takes and then the addon seems to run properly.

**Comment by nihmble** [comment]
> I had to copy what you did, adding `BackdropTemplateMixin and "BackdropTemplate" or nil)` to all places using `CreateFrame`, in the supporting libs. Then it was all working without issue.
> 
> I know you can't update those libs as part of your project but I just wanted to let you know that that's all it takes and then the addon seems to run properly.

Do you have a repo or a PR with that fix?
