### ISSUE TITLE
Lua errors

### ISSUE THREAD

**Issue by spiderman82** [Nevcairiel/Bartender4#41]
1x ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua:1863: AceConfigRegistry-3.0-20:ValidateOptionsTable(): SpartanUI.args.ModSetting.args.Nameplates.enabled: unknown parameter
[string "=[C]"]: ?
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:50: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:45>
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:238: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219>
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:254: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219>
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:254: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219>
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:282: in function `ValidateOptionsTable'
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:324: in function `app'
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:1863: in function `Open'
[string "@SpartanUI\core\Framework.lua"]:2363: in function <SpartanUI\core\Framework.lua:2359>
[string "=[C]"]: ?
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:843: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664>
[string "=[C]"]: ?
[string "@Bartender4\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <...aceBartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Bartender4\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Bartender4\libs\AceGUI-3.0-41\widgets\AceGUIWidget-Button.lua"]:22: in function <...der4\libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>

**Comment by Nevcairiel** [comment]
This is an issue with SpartanUI

**Comment by spiderman82** [comment]
Oh yes? Ok thanks!
