### ISSUE TITLE
Bugs with New Player Experience

### ISSUE THREAD

**Issue by Wutname1** [Nevcairiel/Bartender4#43]
Not sure if you can really do much since it's blizzards code breaking but figured id drop it here anyways. With BT4 enabled you get errors when it tries to tell the player to put items on the bars or click a button. 

4x ...zzard_NewPlayerExperience\Blizzard_TutorialSteps.lua:574: attempt to index local 'button' (a nil value)
[string "@Blizzard_NewPlayerExperience\Blizzard_TutorialSteps.lua"]:574: in function `dispatcherCallback'
[string "@Blizzard_NewPlayerExperience\Blizzard_TutorialDispatcher.lua"]:84: in function `Invoke'
[string "@Blizzard_NewPlayerExperience\Blizzard_TutorialDispatcher.lua"]:188: in function `OnEvent'
[string "@Blizzard_NewPlayerExperience\Blizzard_TutorialDispatcher.lua"]:32: in function <..._NewPlayerExperience\Blizzard_TutorialDispatcher.lua:32>

**Comment by Nevcairiel** [comment]
How do i access the NPE exactly? Can I do it on an old account?

**Comment by Wutname1** [comment]
You can on any new character

**Comment by Wutname1** [comment]
Once you go to make a new character you are presented with an option of Exile's Reach (NPE) on the left or traditional zone 
![image](https://user-images.githubusercontent.com/704321/97484539-d51f9300-1926-11eb-910e-3ee4eca8374b.png)

**Comment by Nevcairiel** [comment]
I played through Exiles Reach on the Beta once and didnt get any errors, but i suppose I can try again.
