### ISSUE TITLE
Keep seeing a weird rectangle as a range indicator

### ISSUE THREAD

**Issue by Fawniie** [Nevcairiel/Bartender4#48]
Hi, thank you for this addon.

I have a weird problem since Shadowlands came out, I keep seeing this weird rectangle on my buttons as a range indicator even though I have range indicators turned off under general settings. Heres a screenshot:
https://i.imgur.com/nBz1Tjf.png

It appears on buttons that don't have a keybind, have hidden keybinds and on the extra button you sometimes get in the middle when doing a quest.

Is there a way to hide this icon/rectangle? Thank you in advance.

**Comment by Nevcairiel** [comment]
This means your chosen font does not include the range indicator icon - which is chosen by Blizzard.
