### ISSUE TITLE
LUA BUG :(

### ISSUE THREAD

**Issue by Hitsuwalker** [Nevcairiel/Bartender4#49]
Message: ...tender4\libs\LibButtonGlow-1.0\LibButtonGlow-1.0.lua:64: attempt to index local 'cooldown' (a number value)
Time: Thu Mar 18 14:48:40 2021
Count: 9761
Stack: ...tender4\libs\LibButtonGlow-1.0\LibButtonGlow-1.0.lua:64: attempt to index local 'cooldown' (a number value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Bartender4\libs\LibButtonGlow-1.0\LibButtonGlow-1.0.lua"]:64: in function <...tender4\libs\LibButtonGlow-1.0\LibButtonGlow-1.0.lua:59>

Hello can you help me to fix this one ?

**Comment by Hitsuwalker** [comment]
It make me lag please if someone can fix this for me :'(

**Comment by Hitsuwalker** [comment]
UP

**Comment by Nevcairiel** [comment]
Some other addon is interfering and breaking things, there is nothing to fix here.
