### ISSUE TITLE
Add dependencies as git submodules

### ISSUE THREAD

**Issue by cannonpalms** [Nevcairiel/Bartender4#5]
References to files & folders within the `/lib` dir only exist within the ZIP files under releases. Some people, such as myself, prefer to manage their addons with git repos to enable updates. 

Please consider adding the missing items from `/lib` as git submodules.

Thanks,
Cannon

**Comment by Nevcairiel** [comment]
The majority of dependencies are not even in Git, so that really wouldn't work.
In any case, I would recommend to install the libraries as stand-alone  in such a  use-case.
