### ISSUE TITLE
Hover scroll triggers

### ISSUE THREAD

**Issue by eVen-gits** [Nevcairiel/Bartender4#6]
Hello,
would it be possible to implement (or is it possible right now) to have scroll triggers on action buttons?

To be more specific, I wonder if it would be possible to scroll on a bound ability to switch it to something else. It would be ideal if it were possible to scroll on an ability in an action bar to select higher or lower rank of the same ability.

**Comment by Nevcairiel** [comment]
No, the secure nature of the buttons does not allow that kind of interactivity.
