### ISSUE TITLE
Moving buttons without triggering them

### ISSUE THREAD

**Issue by 1shka** [Nevcairiel/Bartender4#63]
Hi there. On tbcc we have command "/console ActionButtonUseKeyDown 1" which provides function of use key when pressing down like on retail
1. If unchecked in options bartender blocking this function at all.
2. when checked we have pretty bad version with "use" even if i only want to move my button to another place.

Сan we have completle remove it since we have "/console ActionButtonUseKeyDown 1" by default?

Moving buttons with mouse triggering the usage of them. That function need to work only with keyboard.

4.10.10 version

**Comment by Nevcairiel** [comment]
This should be resolved in the next update.
