### ISSUE TITLE
TBC LFM Button

### ISSUE THREAD

**Issue by mecurc** [Nevcairiel/Bartender4#66]
Since 2.5.2 blizzard adds LFM button but this addon didn't know about that. Atm this looks like this
<img width="301" alt="Screenshot 2021-10-02 at 10 19 06" src="https://user-images.githubusercontent.com/33278950/135707460-07a3afa5-feab-4c6b-862b-a7588b80c36b.png">

(i adds terrible padding for make this button viewable)

**Comment by mecurc** [comment]
I can manually update code, but idk what code i should change

**Comment by skeuomorph-wow** [comment]
Was https://github.com/Nevcairiel/Bartender4/commit/707195ad6c5c111d96a16d6b033a3a2dac56700a tested and working? I tried this locally based on the most recent version from Curse and I had to add `LFGMicroButton` to the CLASSIC list.

**Comment by mecurc** [comment]
Hi! Yes, this patch worked for me. Also I think it's more versatile because if blizzard decide to add another button, it won't need another patch ;-)
