### ISSUE TITLE
9.2 PTR - Bartender blocking new mouseover functionality

### ISSUE THREAD

**Issue by joshuadbeil** [Nevcairiel/Bartender4#68]
Hey, just wanted to give you a little heads up for 9.2.
Title basically says it all. With Bartender enabled, the option to have mouseover cast by default (without setting a keybind for it) doesn't work.
Ty for the awesome addon.

**Comment by Nevcairiel** [comment]
Bartender4 already has built-in mouseover casting, it is however configured independently of the default UI. I looked into the new built-in feature, and its not really advantageous to use it.

If you want to use mouse over casting in Bartender4, set the modifier (or "None") in the general Bar settings, and then enable "Mouse-Over Casting" in the State settings of each bar that you want to be mouse-over enabled.

In the future I might remove the Bartender modifier setting (maybe for DF release), and instead rely on the vanilla modifier.
