### ISSUE TITLE
Add Support for Button Text

### ISSUE THREAD

**Issue by RexBelli** [Nevcairiel/Bartender4#7]
I looked through the code base and did not see support for placing text on action bar buttons -- though I could've missed it.

If it's not there already, is it possible to add support for placing text onto buttons?  This is to enable addons like TheoryCraft and DrDamage to place estimated heal/damage numbers on the ability icons.

**Comment by Nevcairiel** [comment]
Bartender4 creates buttons from the default action button template in the default UI. I would think that it would be up to those addons to support Bartender buttons, similar to how they would support default action bars, instead of the other way around.
