### ISSUE TITLE
TBC - Possess Bar doesnt work on Teron Gorefiend ghost phase

### ISSUE THREAD

**Issue by Nillx** [Nevcairiel/Bartender4#71]
Im wondering if its possible to use the function "Possess bar" on Teron when you get killed by Shadow of Death and transformed into a ghost? 

Currently its using the pet bar above your action bars and we have to use macros, would be nice if the addon auto switches my bar from the default one to the ghost spells when im a ghost.

**Comment by Nevcairiel** [comment]
I don't think the Possess Bar existed back in TBC, and the presence of it is entirely controlled by Blizzard. Action Buttons are protected actions, so I can only do what they let you do.
