### ISSUE TITLE
EXP Bar unusable when tracking reputation + scale way too small

### ISSUE THREAD

**Issue by addonaddict** [Nevcairiel/Bartender4#72]
Below image is when using stacked bars mode
For some reason - instead of reusing blizzard's enlarged bar, the longer bar is used here scaled down so that text is down right unreadable, even at 1.00 UI scale at 1080p.
Adding rep tracking to it, you might as well disable the module all together.
A separate addon is required at the moment for exp bar.

Is any improvement possible? Even Dominos deals with exp bar pretty badly and all the standalone addons for exp bar are terrible and dont match the UI.

![image](https://user-images.githubusercontent.com/73442541/159210922-c575ac8f-4cdf-4d3c-a0ac-a72a2e655a30.png)

this image below is blizz standard exp bar.. shortened when using stacked bars mode
![image](https://user-images.githubusercontent.com/73442541/159211161-448008d5-b0fd-4239-8bb6-82a4d9f43bad.png)

Thanks

**Comment by Nevcairiel** [comment]
I've added an option to change the bars width instead of only the scale, as well as toggle between 20 and 10 sections.

**Comment by tanrak** [comment]
Hi, i can't find the option to change the bars width instead of the scale. Does this option exist in the version for wotlk classic?
