### ISSUE TITLE
[TBC Classic] Bartender causing micro stutter/game freeze

### ISSUE THREAD

**Issue by Calzeru** [Nevcairiel/Bartender4#74]
Bartender is suddenly causing lag spikes whenever player models load in. Not sure when it started, possibly with Zul'Aman release a week or so ago.
More info here:
https://www.wowace.com/projects/bartender4/issues/1835

**Comment by nlenzner** [comment]
Can confirm this one, I have this problem for a few days, tried to separately activate all addons one by one and these short freezes only appear when bartender is active.

**Comment by Laumesis** [comment]
Same here

**Comment by Nillx** [comment]
Noticed this on retail as well. Game runs fine when BT is disabled.
