### ISSUE TITLE
[WRATH] Missing shadow dance state configuration

### ISSUE THREAD

**Issue by XyzKangUI** [Nevcairiel/Bartender4#76]
Currently in wrath classic there is no state configuration for shadow dance like there is for stealth. 

With custom conditions you can have it properly working by using [form:1] for stealth and [form:2] for shadow dance. 

These will add the missing state option:
`{ id = "dance", name = GetSpellInfo(51713), index = 2 },` in StateBar.lua
`ROGUE = { stealth = 7, dance = 8 },` in ActionBars.lua

Although in statebar.lua it would require to have a new boolean like the WoWBC one.

**Comment by Nevcairiel** [comment]
Does Blizzard swap automatically on shadowdance, if so where to? Is it wanted to swap to a different bar, or the stealth bar?

**Comment by XyzKangUI** [comment]
> Does Blizzard swap automatically on shadowdance, if so where to? Is it wanted to swap to a different bar, or the stealth bar?

It swaps to bonusbar2, which is a different bar than stealth/vanish.
