### ISSUE TITLE
Totem bar support for Wrath Classic

### ISSUE THREAD

**Issue by nteetor** [Nevcairiel/Bartender4#77]
I'm using Bartender on the WotLK Beta and noticed the Shaman totem bar isn't visible. I thought maybe I needed to enable something, but I couldn't find any options for the totem bar. If I disable Bartender I'm able to see the default totem bar. I'm using version 4.11.3 on the Beta.

Is this a feature Bartender will support or is supposed to support?

**Comment by Nevcairiel** [comment]
I'm going to add totem bar support in some fashion before Wrath goes live.

**Comment by nteetor** [comment]
Great to hear, thank you!

**Comment by NorbertasL** [comment]
> Added in [64827f4](https://github.com/Nevcairiel/Bartender4/commit/64827f4c5be2e947044b8653e70bdba6625760c0)

I still cant see the totem bar :(. I reset all setting and still nothing.
Running the latest version  4.11.3-7-g3b665c2

**Comment by Nevcairiel** [comment]
The game controls when the bar is shown, Bartender just makes it movable. Do you mean it doesn't show when no talent points are spent? Not sure I could reproduce that

**Comment by NorbertasL** [comment]
> The game controls when the bar is shown, Bartender just makes it movable. Do you mean it doesn't show when no talent points are spent? Not sure I could reproduce that

So this is what happened. I logged onto the PTR and made a 70 toon. When bartender was off I could see the totem bar, but when it was on I could not. Did a full reset of bartended and it didn't help. After i started specing into the talents the bar just popped out in the middle of the screen.
