### ISSUE TITLE
What if click through at the bar slot that a skill is not dragged into?

### ISSUE THREAD

**Issue by wolfcon** [Nevcairiel/Bartender4#8]

**Comment by Wutname1** [comment]
Are you saying you want to be able to click through a bar? This is already an option.

![image](https://user-images.githubusercontent.com/704321/64940171-da0bab00-d828-11e9-8fbb-47c8e4405422.png)

**Comment by Nevcairiel** [comment]
Empty buttons cannot be click-through, the secure system in WoW doesn't allow that without breaking a bunch of stuff in combat.
