### ISSUE TITLE
Dragonflight Beta support please

### ISSUE THREAD

**Issue by Voxxel** [Nevcairiel/Bartender4#80]
I see it's wotlk time for fixes/updates but I hope Bartender4 will be available for Dragonfight Beta soon too. Addons are now enabled but BT4 is completely broken unfortunately. :(

**Comment by Nevcairiel** [comment]
Addon support in the beta is currently very broken and its impossible to make a custom  action bar addon like Bartender work.

So think more like weeks rather then days.

**Comment by Voxxel** [comment]
I'm pretty glad if it's on your table at all. :)

**Comment by Aerisot** [comment]
Bartender seems to be working for me in DF with its current build.

Only issues I am experiencing so far are the following.

1) Bartender Bar 1, does not change over to the Dragon riding bar when hoping on a dragon, had to place the action buttons on a new bar and key bind them.

2) The size of the bars keeps resetting back to .85 every time I log out for an extended period of time.

Other than those, it seems to be working well.

**Comment by kingreboot** [comment]
not sure what you did, but everything was broken for Bartender on Beta for me

**Comment by nulian** [comment]
Probably got version from current master that one is mostly working but doesn't have release version for it.

**Comment by kingreboot** [comment]
that makes sense

**Comment by Aerisot** [comment]
> not sure what you did, but everything was broken for Bartender on Beta for me

Honestly, I just downloaded the new alpha release, Not sure what would be different from your current version, it still has some issues, but it is working for the most part.

**Comment by Nevcairiel** [comment]
The Alpha version available on CurseForge should work reasonable well these days, baring any new issues created after every beta update.
