### ISSUE TITLE
[WotLK] Micro Menu is missing some (new) items

### ISSUE THREAD

**Issue by Zereges** [Nevcairiel/Bartender4#81]
In wrath prepatch, the (BT4) micro menu currently contains Character Info, Talents, Quest Log, PvP, Game Menu. Although the original (Blizzard) *micro menu* contains Character Info, Spellbook, Talents, Achievements, Quest Log, Social, PvP, Group Finder, Game Menu, Help.

Would it be possible to add the items to the Micro menu (most ideally with option to selectively enable/disable individual items).

**Comment by Nevcairiel** [comment]
I have tested just now, and the buttons on the micro menu are identical for me with or without BT4.

**Comment by Zereges** [comment]
> I have tested just now, and the buttons on the micro menu are identical for me with or without BT4.

Ah, the issue is that if you set *Rows* for *Micro Menu* to anything else than 10 (e.g. 9) some buttons will disappear. Thanks anyway!
