### ISSUE TITLE
Shadowform no longer swaps bars in WOTLK Pre-Patch.

### ISSUE THREAD

**Issue by ksulli10** [Nevcairiel/Bartender4#82]
Going into Shadowform used to swap the bars which allowed me to use the same keybinds for each. This is no longer the case. Going into Shadowform keeps my non-Shadowform bar visible and uses the old bar's keybinds. This pops me out of Shadowform every time because it casts a holy spell that is bound on my non-Shadowform bar.

Is this a functionality change that happened on Blizzard's side? Or is this unintended for Bartender?

**Comment by Korenn** [comment]
The options for shadow form state management have disappeared. I guess it could be solved with a custom condition, but who knows how to actually use that arcane thing.

**Comment by Nevcairiel** [comment]
This should already be supported in the latest alpha version, will make a release later today.
