### ISSUE TITLE
Possessbar/Pet Bar

### ISSUE THREAD

**Issue by pquerner** [Nevcairiel/Bartender4#83]
Hey, I have this wierd glitch which is making me crazy. Maybe there is a solution.

I am playing Wrath Classic and whenever I control a machine and I hit my PPT key (Mouse5), it hits the same key "on the dragon" (ie. exit-vehicle).
I dont want that obviously ;)

So I have disabled "Possessed bar" which fixes that error - but it creates a new one. There is a boss in Drak'Tharon Keep [1] which turns you into a skelleton - with its own action bar and spells.

When I have "Posssessed" bar off I no longer have said bar and cannot use any spells of that skeleton.
I reckon its not that "bad" in the heroic instance (yet, wait for heroic plus?) but I dont know if it happens ie. in a raid when you get to control anything. (being a priest in Naxxramas 25?).

Is that my "doing" or is there a step I am missing - possibly without altering/changing my PPT keys. ^^ 

[1] https://www.youtube.com/watch?v=LHoBFSAVWyM

**Comment by pquerner** [comment]
More info:

https://i.imgur.com/HNTkn4J.jpeg
The button (action) on B5 (Mousebutton5) is pressed "in the background" when I am inside a Vehicle (here Dragon, during the Quest "Aces High!" in Coldarra).

In this screenshot I've just enabled to see the actionbar - normally its hidden (but action is still pressed)

fstack:

https://i.imgur.com/6DO1EE4.png
(hover from the leave-vehicle button)

normal leave-vehicle button:
https://i.imgur.com/eFW6Z9d.jpeg

**Comment by pquerner** [comment]
Tracked it down to 

`BT4ActionBars:ReassignBindings`

this fixes it for me:

```
if key and key ~= "" then
				if i ~= 12 then
					SetOverrideBindingClick(frame, false, key, real_button)
				end
			end
```

basically ignoring the last button from actionbar1.

I do not know if it yields any side effects.
Tested scenarios:

- switch keybind (of any button in actionbar1)
- switch keybind of button 12 of actionbar1
- /reload ui
- teleport away, fly to test location again (teleport to dalaran > loading screeen)

maybe you could integrate that or explain why it behaves like that? ^^

Meanwhile I try to hook that func, but I am not that good with lua. can you kick me in the right direction?

```
local BT4ActionBars = Bartender4:GetModule("ActionBars")
local onEnable = BT4ActionBars.OnEnable

function BT4ActionBars:OnEnable()
	onEnable(self)
    
    if InCombatLockdown() then return end    
	if not self.actionbars or not self.actionbars[1] then return end
	
	hooksecurefunc(self.actionbars[1], "ReassignBindings", function(self, event)
		print("yay5")
	end)
	
	self.OnEnable = onEnable
end
```

**Comment by Nevcairiel** [comment]
I don't understand why your PPT key is bound to any action button in the first place. You clearly never want any action to happen when you speak? If you don't want to change your PPT key, just unbind it from doing anything in game?

**Comment by pquerner** [comment]
Yes its odd, and I already said these two solutions exists. I am just baffled why this is doing something (differently) using Bartenders4 and not other ActionBar AddOns.

You may close this issue if you dont think its odd, its super fine. :)

(Although if  you can I would appreciate a word about how  to hook that function so I can "fix" it in a extending-addon. I can also just read up and keep trying. Just if you see anything in 1 go I would appreciate a hint in the right direction.)
