### ISSUE TITLE
[WotLK Classic] Entering a vehicle while in-combat causes problems

### ISSUE THREAD

**Issue by silverhawke249** [Nevcairiel/Bartender4#84]
This is most evident in Malygos encounter in Eye of Eternity:
- The vehicle UI does not appear
- Bar 1 gets replaced with what would have been on the vehicle UI
- Keybinds on Bar 1 stops working, necessitating clicking on the buttons

**Comment by Nevcairiel** [comment]
Try using the latest alpha version from CurseForge, it may already be fixed, but I can't easily test.

**Comment by silverhawke249** [comment]
I will give it a shot and let you know here.

**Comment by Nevcairiel** [comment]
I've tried on the shredder daily in Grizzly Hills, and with or without blizzard vehicle UI enabled, the transition seems to be fine here.
