### ISSUE TITLE
[WotLK Classic] Entering a vehicle does not hide action bars

### ISSUE THREAD

**Issue by silverhawke249** [Nevcairiel/Bartender4#85]
The built-in action bars hide themselves on entering a vehicle. One consequence of this is that the Blizzard quest tracker shifts right while inside a vehicle.
However, Bartender's action bars stays visible, causing the quest tracker to overlap.

**Comment by Nevcairiel** [comment]
Every bar has a setting to hide it on a vehicle (which should be set by default), however if those don't work then Blizzard likely broke the condition required to trigger it.

**Comment by silverhawke249** [comment]
This one is my mistake, my bad. My bars wasn't set to hide on vehicle for some reason, I had to manually set them all to hide.
