### ISSUE TITLE
queue eye in dragonflight 10.0.0

### ISSUE THREAD

**Issue by silentwar-resident** [Nevcairiel/Bartender4#86]
in dragonlight 10.0.0, 

will bartender4 be fixed to include the queue eye  as bartender4? like this... 

![image](https://user-images.githubusercontent.com/33927568/194786051-4b838ea4-830a-474b-ae1f-cbe1969e3a17.png)

because when i used bartender4 in dragonflight on ptr,  the quenue eye disappeared  as in the picture above before bartender was installed.

Thanks....

**Comment by MetalMusicMan** [comment]
I'm still not getting the green LFG eye on my Micro Menu, anyone have any info?
