### ISSUE TITLE
Dragonflight UI Art

### ISSUE THREAD

**Issue by DT85** [Nevcairiel/Bartender4#88]
My idea is to add an option to use the new dragonflight actionbar art, but with the old actionbar layout. Would probably need a few custom textures, which I'd be willing to help with.

**Comment by Nevcairiel** [comment]
Which old layout is that?

Shadowlands for example is not actually too different from DF, just a bit wider (12 buttons vs. 18).
Making the two book-ends further apart, or shrinking the buttons a bit to accomodate more would be relatively easy, as the buttons are generated individually, and not part of a big texture. Maybe I could even add an option to let users control the number of buttons in the DF Art.

**Comment by DT85** [comment]
Sorry I meant using the dragonflight art with the retail shadowlands layout. 

I've made a prototype (currently overwriting the dwarf bar textures) with DF's griffin endcaps and button backgrounds while also accommodating the extra reagent bag:

![Bartender DF](https://user-images.githubusercontent.com/4074193/195744355-dc26065b-6bd8-4ab1-b375-7be0b1f2528b.png)

I have the art for the wyvern endcap done as well.

**Comment by Nevcairiel** [comment]
But thats not the Shadowlands layout. Shadowlands already moved the micro menu and the bags out of the actionbar cluster, like DF. Hence me asking.

**Comment by DT85** [comment]
Apologies for my confusion. I'm meaning to add DF art options to the Classic layout option in bartender.

**Comment by DT85** [comment]
I think this looks better, I ditched the custom art textures and just used the dragonflight art from in the game: 

![WoWScrnShot_101722_143051](https://user-images.githubusercontent.com/4074193/196090000-1c0c30bd-a882-4ed4-9a22-7333de6c2ea1.png)

It's just a copy of the art bar border, with 1 divider to separate the menu and bags,  then the actionbar background with rgb set to 0.1 so it's not super dark and not transparent.
