### ISSUE TITLE
Evoker Empower not working in DF Beta

### ISSUE THREAD

**Issue by MetalMusicMan** [Nevcairiel/Bartender4#90]
I cannot release empowered Evoker spells with Bartender on the DF Beta. It does not even begin casting if I hold down the button, instead it just sits as if I am not casting the spell at all. When I release the button, the Empowered spell begins casting, but I cannot release the empower level. I can only cancel it or let it fully empower (and hold for the extra time at the end). 

Turning off Bartender and using the default Drangonflight action bars fixes this.

**Comment by Nevcairiel** [comment]
This is a Blizzard issue on the beta currently, but hopefully getting fixed in this weeks update.

**Comment by Nevcairiel** [comment]
This is now resolved in the beta.
