### ISSUE TITLE
EnableBar(n) and DisableBar(n) only work for n<=6

### ISSUE THREAD

**Issue by fabiang7** [Nevcairiel/Bartender4#94]
Bartender4:GetModule("ActionBars"):EnableBar(7) and
Bartender4:GetModule("ActionBars"):DisableBar(7)
does not work. 

Only n = 1 ... 6 works

How to reproduce:
Run the following Macros ingame:
/run local bars, barMod = {2,3,4,5,6,7}, Bartender4:GetModule("ActionBars"); for _, n in pairs(bars) do barMod:EnableBar(n) end

/run local bars, barMod = {2,3,4,5,6,7}, Bartender4:GetModule("ActionBars"); for _, n in pairs(bars) do barMod:DisableBar(n) end

they will only toggle bars 2,3,4,5,6 but not 7.

**Comment by Nevcairiel** [comment]
I just ran Bartender4:GetModule("ActionBars"):EnableBar(7)  and it works fine.

Note that directly messing with the API is not something I'll endorse - if you want to change configuration in a macro etc, you can use the command line interface, for example `/bt bars 7 enabled on` to enable a given bar.

Note that the indices user here do not match the public naming of the bars. Bar 7 is actually Class Bar 1.

**Comment by fabiang7** [comment]
Oh! I am sorry! Didn't know that. So I try to use your suggestion with /bt bars.
