### ISSUE TITLE
Add more paging options

### ISSUE THREAD

**Issue by Soromeister** [Nevcairiel/Bartender4#95]
Please have feature parity with [Dominos](https://github.com/tullamods/Dominos) with regards to paging options. Request is to have this visually configurable.

![image](https://user-images.githubusercontent.com/45243695/198147021-bb37b2db-659e-4eca-9439-1fdba3be236a.png)
![image](https://user-images.githubusercontent.com/45243695/198147443-6ccf6154-470b-493a-abb2-b0ea0d0eff80.png)
![image](https://user-images.githubusercontent.com/45243695/198147491-d64350f3-ee7a-4086-a079-292a818e057c.png)
![image](https://user-images.githubusercontent.com/45243695/198147529-4ca28b35-1f4c-4e93-8cd6-f5467227ef35.png)

**Comment by Nevcairiel** [comment]
Bartender supporst the vast majority of those already, and any other more rarely used conditions can be used through the custom conditionals.

If you are missing any one thing in particular, its fine to request, but broad sweeping "i want parity" requests are not helpful to guide decisions on what to implement in the future.
