### ISSUE TITLE
Button lock auto turn on

### ISSUE THREAD

**Issue by KonstantinosKoubetsos** [Nevcairiel/Bartender4#98]
It turns itself on all the time. It might be that I am using "toggle actions on key press" option, but anyways I turn it off and after logout and /reload (the ones I have noticed so far) it turns itself back on.

**Comment by Nevcairiel** [comment]
Button Lock does intentionally not save, as both the message and the tooltip say. I would strongly recommend to using Shift-Drag at all times, which always works, even when locked.
